In [1]:
import json

In [150]:
with open('data/users.json') as f:
    data = json.load(f)

In [151]:
frame = pd.DataFrame(data)

In [152]:
frame

,name,email,address,phone
0,Elsy Hurd,elsyhurd@gmail.com,"- 93 Harvey St, Framingham, MA , US, 01701",751-704-6749
1,Blaire Condon,blairecondon@gmail.com,"845 - 910 Linda St, Rock Hill, SC , US, 29730",118-721-2913
2,Morgan Hansen,morganhansen@gmail.com,"754 - 945 Lakewood Ave, Central Islip, NY , US...",121-866-3016
3,Emmey Kirwin,emmeykirwin@gmail.com,"- 266 Sherwood Circle, Potomac, MD , US, 20854",732-918-9919
4,Kellen Millman,kellenmillman@gmail.com,"592 - 600 East Kirkland St, Duarte, CA , US, 9...",725-811-5736
...,...,...,...,...
2495,Alene Garling,alenegarling@gmail.com,"- 33 SW. Arnold Court, Burbank, IL , US, 60459",169-525-2808
2496,Joli Deck,jolideck@gmail.com,"716 - 2 Bohemia Court, Herndon, VA , US, 20170",473-134-350
2497,Madlen Pang,madlenpang@gmail.com,"883 - 365 Randall Mill Street, Hamden, CT , US...",13-55-7256
2498,Dalia Bigod,daliabigod@gmail.com,"547 - 7868 Taylor Drive, El Dorado, AR , US, 7...",728-358-257
2499,Teodora Abie,teodoraabie@gmail.com,"137 - 4 Fordham Drive, Pittsburgh, PA , US, 15206",203-35-3179

In [153]:
frame = pd.concat([frame, pd.DataFrame(list(frame['address'].apply(lambda x: x.split(","))), columns=["street","city", "state","country", "postal"])], axis=1)
del frame['address']

In [154]:
frame['unit'] = frame['street'].apply(lambda x: x.split(' - ')[0] if '-' in x else None)

In [155]:
frame

,name,email,phone,street,city,state,country,postal,unit
0,Elsy Hurd,elsyhurd@gmail.com,751-704-6749,- 93 Harvey St,Framingham,MA,US,01701,
1,Blaire Condon,blairecondon@gmail.com,118-721-2913,845 - 910 Linda St,Rock Hill,SC,US,29730,845
2,Morgan Hansen,morganhansen@gmail.com,121-866-3016,754 - 945 Lakewood Ave,Central Islip,NY,US,11722,754
3,Emmey Kirwin,emmeykirwin@gmail.com,732-918-9919,- 266 Sherwood Circle,Potomac,MD,US,20854,
4,Kellen Millman,kellenmillman@gmail.com,725-811-5736,592 - 600 East Kirkland St,Duarte,CA,US,91010,592
...,...,...,...,...,...,...,...,...,...
2495,Alene Garling,alenegarling@gmail.com,169-525-2808,- 33 SW. Arnold Court,Burbank,IL,US,60459,
2496,Joli Deck,jolideck@gmail.com,473-134-350,716 - 2 Bohemia Court,Herndon,VA,US,20170,716
2497,Madlen Pang,madlenpang@gmail.com,13-55-7256,883 - 365 Randall Mill Street,Hamden,CT,US,06514,883
2498,Dalia Bigod,daliabigod@gmail.com,728-358-257,547 - 7868 Taylor Drive,El Dorado,AR,US,71730,547
2499,Teodora Abie,teodoraabie@gmail.com,203-35-3179,137 - 4 Fordham Drive,Pittsburgh,PA,US,15206,137

In [158]:
frame['street'] = frame['street'].apply(lambda x: x.split(' - ')[1])

In [159]:
frame

,name,email,phone,street,city,state,country,postal,unit
0,Elsy Hurd,elsyhurd@gmail.com,751-704-6749,93 Harvey St,Framingham,MA,US,01701,
1,Blaire Condon,blairecondon@gmail.com,118-721-2913,910 Linda St,Rock Hill,SC,US,29730,845
2,Morgan Hansen,morganhansen@gmail.com,121-866-3016,945 Lakewood Ave,Central Islip,NY,US,11722,754
3,Emmey Kirwin,emmeykirwin@gmail.com,732-918-9919,266 Sherwood Circle,Potomac,MD,US,20854,
4,Kellen Millman,kellenmillman@gmail.com,725-811-5736,600 East Kirkland St,Duarte,CA,US,91010,592
...,...,...,...,...,...,...,...,...,...
2495,Alene Garling,alenegarling@gmail.com,169-525-2808,33 SW. Arnold Court,Burbank,IL,US,60459,
2496,Joli Deck,jolideck@gmail.com,473-134-350,2 Bohemia Court,Herndon,VA,US,20170,716
2497,Madlen Pang,madlenpang@gmail.com,13-55-7256,365 Randall Mill Street,Hamden,CT,US,06514,883
2498,Dalia Bigod,daliabigod@gmail.com,728-358-257,7868 Taylor Drive,El Dorado,AR,US,71730,547
2499,Teodora Abie,teodoraabie@gmail.com,203-35-3179,4 Fordham Drive,Pittsburgh,PA,US,15206,137

In [149]:
frame

,name,email,phone,street,city,state,country,postal,unit
0,Elsy Hurd,elsyhurd@gmail.com,751-704-6749,93 Harvey St,Framingham,MA,US,01701,None
1,Blaire Condon,blairecondon@gmail.com,118-721-2913,845 - 910 Linda St,Rock Hill,SC,US,29730,845
2,Morgan Hansen,morganhansen@gmail.com,121-866-3016,754 - 945 Lakewood Ave,Central Islip,NY,US,11722,754
3,Emmey Kirwin,emmeykirwin@gmail.com,732-918-9919,266 Sherwood Circle,Potomac,MD,US,20854,None
4,Kellen Millman,kellenmillman@gmail.com,725-811-5736,592 - 600 East Kirkland St,Duarte,CA,US,91010,592
...,...,...,...,...,...,...,...,...,...
2495,Alene Garling,alenegarling@gmail.com,169-525-2808,33 SW. Arnold Court,Burbank,IL,US,60459,None
2496,Joli Deck,jolideck@gmail.com,473-134-350,716 - 2 Bohemia Court,Herndon,VA,US,20170,716
2497,Madlen Pang,madlenpang@gmail.com,13-55-7256,883 - 365 Randall Mill Street,Hamden,CT,US,06514,883
2498,Dalia Bigod,daliabigod@gmail.com,728-358-257,547 - 7868 Taylor Drive,El Dorado,AR,US,71730,547
2499,Teodora Abie,teodoraabie@gmail.com,203-35-3179,137 - 4 Fordham Drive,Pittsburgh,PA,US,15206,137

In [160]:
import pandas as pd

In [161]:
frame = pd.read_csv('data/properties.csv')

In [162]:
frame[['postal','state']] = frame[['state','postal']]

In [166]:
frame['unit'].apply(lambda x: int(x) if x is not None else x)

ValueError: cannot convert float NaN to integer

In [107]:
import glob
import ast,re

In [124]:
def extract_data(data):
    try:
        return ast.literal_eval(re.search('({.+})', data).group(0))
    except:
        return { "email": None, "type": None, "message": None}

In [125]:
frame = pd.DataFrame()
for file in glob.glob("data/events/*.txt"):
    with open(file) as f:
        data = f.read()
    df = pd.DataFrame(data.split('\n'),columns=['logs'])
    df['timestamp'] = df['logs'].apply(lambda x: x.split(' GMT')[0])
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['data'] = df['logs'].apply(lambda x: extract_data(x))
    df = pd.concat([df,df['data'].apply(pd.Series)], axis=1)
    del df['logs']
    del df['data']
    frame = frame.append(df)
frame = frame.dropna()

In [130]:
frame

,timestamp,email,type,message
0,2021-11-13 12:00:21,olamandle@gmail.com,info,eu velit mollit velit
1,2021-11-13 12:00:31,olamandle@gmail.com,log,exercitation et et proident sit veniam
2,2021-11-13 12:00:53,olamandle@gmail.com,log,est elit eiusmod consectetur laboris
3,2021-11-13 12:01:16,olamandle@gmail.com,warn,adipisicing reprehenderit officia
4,2021-11-13 12:01:41,olamandle@gmail.com,info,eu ullamco cillum deserunt
...,...,...,...,...
9,2021-10-05 12:02:31,joleemilburn@gmail.com,info,veniam ut eiusmod consequat reprehenderit
10,2021-10-05 12:02:35,joleemilburn@gmail.com,debug,est non magna veniam
11,2021-10-05 12:02:49,joleemilburn@gmail.com,test,adipisicing
12,2021-10-05 12:03:19,joleemilburn@gmail.com,debug,reprehenderit deserunt laboris amet aliqua ex
13,2021-10-05 12:03:47,joleemilburn@gmail.com,debug,do aute sunt

In [105]:
df

,timestamp,email,type,message
0,2021-12-03 12:00:23,adelinabenco@gmail.com,debug,laborum do dolor minim sint eu
1,2021-12-03 12:00:24,adelinabenco@gmail.com,warn,quis minim deserunt ipsum est ea